### ISSUE TITLE
Add suggestions to the reading list

### ISSUE THREAD

**Issue by dcwalk** [cryptographydog/december-meetup#1]
A "reading pool" doc was set up to collect a range of potential readings: https://hackmd.io/_vUINRdvR1qlry3B5aNXqw?edit#

**Comment by benhylau** [comment]
Given this may become an ongoing list that will exist somewhere, I suggest we commit a snapshot https://github.com/cryptographydog/december-meetup/pull/15 and close the issue

**Comment by dcwalk** [comment]
Makes sense!

**Comment by patcon** [comment]
Posting here for now bc I'm in mobile and hackmd ain't great for that:

Enspiral Founders next project, soliciting feedback: https://medium.com/enspiral-tales/courage-before-hope-a-proposal-to-weave-emotional-and-economic-microsolidarity-87bc81372a09
