### ISSUE TITLE
Finalize venue for retreat

### ISSUE THREAD

**Issue by dcwalk** [cryptographydog/december-meetup#12]
From [Oct 31 meeting](https://github.com/cryptographydog/december-meetup/blob/master/2018-10-31-meeting-retreat-planning-2.md), we agreed we need to:

- Set up venue (e.g. inperson component? remote?)

**Comment by benhylau** [comment]
@uditvira looks like it will be completely remote and on Loomio? Let's chat on Wed about this.

**Comment by dcwalk** [comment]
We've said full remote a couple times, so I guess it is!
