### ISSUE TITLE
Add bits from the initial planning doc somewhere?

### ISSUE THREAD

**Issue by dcwalk** [cryptographydog/december-meetup#13]
I'm wondering if we want to integrate notes from the initial planning doc @benhylau spun up somewhere: https://hackmd.io/BqPYmfK1RfCRG7Yi_aEk0A#

**Comment by benhylau** [comment]
Thanks for posting this. I think this and the linked-to docs (except the Toronto Mesh one) should be in our meeting history.

**Comment by benhylau** [comment]
I have made PRs for everything. Please close after all are merged.

**Comment by dcwalk** [comment]
They are merged! Closing as done 🕺
